development:
  adapter: postgresql
  encoding: unicode
  database: kiiiosk_development_2
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: kormilica_test
  pool: 5
  username:
  password:

staging:
  adapter: postgresql
  encoding: unicode
  database: kormilica_test
  pool: 5
  username:
  password:

production:
  adapter: <%= ENV["OPENBILL_DATABASE_ADAPTER"] %>
  encoding: unicode
  database: <%= ENV["OPENBILL_DATABASE_NAME"] %>
  pool: <%= ENV["OPENBILL_DATABASE_POOL"] %>
  host: <%= ENV["OPENBILL_DATABASE_HOST"] %>
  port: <%= ENV["OPENBILL_DATABASE_PORT"] %>
  username: <%= ENV["OPENBILL_DATABASE_USERNAME"] %>
  password: <%= ENV["OPENBILL_DATABASE_PASSWORD"] %>
